project_id = "vaxxrwnfcaxvqvdhlsad"

[functions.advisor]
verify_jwt = true

[functions.analyze-floor-plan]
verify_jwt = true

[functions.create-connect-account]
verify_jwt = true

[functions.detect-clashes]
verify_jwt = true

[functions.generate-qr-code]
verify_jwt = true

[functions.process-bim-file]
verify_jwt = true

[functions.send-email]
verify_jwt = true

[functions.update-as-built]
verify_jwt = true

[functions.verify-compliance]
verify_jwt = true