// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vaxxrwnfcaxvqvdhlsad.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZheHhyd25mY2F4dnF2ZGhsc2FkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzUxNzYwMDYsImV4cCI6MjA1MDc1MjAwNn0.NiT_5z5UXLZB5VBZHW2k_p1e0HstxR2_FFyXpzuE4zc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);